spring:
  application:
    name: authentication
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    jedis:
      pool:
        max-active: 10
        max-idle: 5
        min-idle: 1
    timeout: 60000

server:
  port: ${SERVER_PORT}
security:
  jwt:
    secret: ${SECURITY_JWT}
clients:
  header:
    key: ${CLIENTS_HEADER_KEY}
  email-sender:
    url: ${CLIENTS_EMAIL-SENDER_URL}